name: med_quiz_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0            # GitHub-dan məlumat çəkmək üçün
  path_provider: ^2.1.1   # Faylları telefonda saxlamaq üçün
  shared_preferences: ^2.2.2 # Hash və Broadcast ID saxlamaq üçün
  crypto: ^3.0.3          # (Opsional) Hash yoxlaması üçün lazımdırsa
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/app_icon.png" # Çevirdiyin PNG faylı
  # Android üçün adaptiv ikon tənzimləmələri
  adaptive_icon_background: "#5DA9E9" # Sənin SVG-dəki üst gradient rəngi
  adaptive_icon_foreground: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
